apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendfitcart-ingress
  namespace: dev-crud-app
  annotations:
    appgw.ingress.kubernetes.io/health-probe-path: "/api/gym/records"
    
spec:
  ingressClassName: azure-application-gateway
  rules:
 - host: ashvani.shop
   http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fitcart-backend-service
            port:
              number: 8080

    
