name: CI-AKS-ACR

on:
   workflow_dispatch:

permissions:
  contents: read

jobs:
  build_scan_push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: tag
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: Login to ACR
        run: |
          az acr login --name devnitoracr001

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy --version

      # Build Backend Image
      - name: Build Backend Image
        run: |
          docker build \
            -t devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.sha }} \
            ./3-tier-app-fitcart/backend

      # Scan Backend Image
      - name: Scan Backend Image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 0 \
          devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.sha }}

      # Push Backend Image
      - name: Push Backend Image
        run: |
          docker push \
          devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.sha }}

      # Build Frontend Image
      - name: Build Frontend Image
        run: |
          docker build \
            -t devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.sha }} \
            ./3-tier-app-fitcart/frontend

      # Scan Frontend Image
      - name: Scan Frontend Image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 0 \
          devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.sha }}

      # Push Frontend Image
      - name: Push Frontend Image
        run: |
          docker push \
          devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.sha }}

 
