name: CI-CD-AKS-ACR

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_scan_push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: tag
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: Login to ACR
        run: |
          az acr login --name devnitoracr001

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy --version

      # Build Backend Image
      - name: Build Backend Image
        run: |
          docker build \
            -t devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.sha }} \
            ./3-tier-app-fitcart/backend

      # Scan Backend Image
      - name: Scan Backend Image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 0 \
          devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.sha }}

      # Push Backend Image
      - name: Push Backend Image
        run: |
          docker push \
          devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.sha }}

      # Build Frontend Image
      - name: Build Frontend Image
        run: |
          docker build \
            -t devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.sha }} \
            ./3-tier-app-fitcart/frontend

      # Scan Frontend Image
      - name: Scan Frontend Image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 0 \
          devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.sha }}

      # Push Frontend Image
      - name: Push Frontend Image
        run: |
          docker push \
          devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.sha }}

  deploy:
    needs: build_scan_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Install kubectl
      # - name: Setup kubectl
      #   uses: azure/setup-kubectl@v4

      # Set AKS Context
      # - name: Set AKS Context
      #   uses: azure/aks-set-context@v4
      #   with:
      #     resource-group: dev-nitor-rg-002
      #     cluster-name: dev-nitor-cluster-01
      
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group dev-nitor-rg-002 --name dev-nitor-cluster-01 --overwrite-existing
          
      # Verify AKS Connection
      # - name: Verify Cluster
      #   run: |
      #     kubectl config current-context
      #     kubectl cluster-info
      #     kubectl get nodes
      #     kubectl get ns

      # Install Helm
      - name: Setup Helm
        uses: azure/setup-helm@v4

      # Lint Helm Chart
      - name: Helm Lint
        run: |
          helm lint ./3-tier-app-fitcart/helm/crud-app-chart

      # Deploy using Helm
      - name: Helm Deploy
        run: |
          helm upgrade --install crud-app ./3-tier-app-fitcart/helm/crud-app-chart \
            --namespace crud-app \
            --create-namespace \
            --wait \
            --timeout 10m \
            --set backend.image.repository=devnitoracr001.azurecr.io/backendimage \
            --set backend.image.tag=${{ needs.build_scan_push.outputs.image_tag }} \
            --set frontend.image.repository=devnitoracr001.azurecr.io/frntndimage \
            --set frontend.image.tag=${{ needs.build_scan_push.outputs.image_tag }}
     # Verify rollout
      - name: Verify Deployment Rollout
        run: |
            kubectl rollout status deployment/fitcart-backend -n crud-app --timeout=5m
            kubectl rollout status deployment/fitcart-frontend -n crud-app --timeout=5m
     
      # Verify Deployment
      # - name: Verify Deployment
      #   run: |
      #     kubectl get all -n crud-app
