name: CI-AKS-ACR

on:
 workflow_dispatch:
    # tags:
    #   - "v*"

permissions:
  contents: read

jobs:
  build_scan_push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Image Tag
        id: tag
        run: |
          IMAGE_TAG=${GITHUB_REF_NAME}
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Using Image Tag: $IMAGE_TAG"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name devnitoracr001

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Build Backend Image
        run: |
          docker build \
            -t devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.image_tag }} \
            ./3-tier-app-fitcart/backend

      - name: Scan Backend Image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 0 \
          devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.image_tag }}

      - name: Push Backend Image
        run: |
          docker push devnitoracr001.azurecr.io/backendimage:${{ steps.tag.outputs.image_tag }}

      - name: Build Frontend Image
        run: |
          docker build \
            -t devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.image_tag }} \
            ./3-tier-app-fitcart/frontend

      - name: Scan Frontend Image
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 0 \
          devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.image_tag }}

      - name: Push Frontend Image
        run: |
          docker push devnitoracr001.azurecr.io/frntndimage:${{ steps.tag.outputs.image_tag }}
